<?php

namespace Fiona\Geektic\CoreBundle\Repository;

/**
 * GeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeekRepository extends \Doctrine\ORM\EntityRepository
{



    public function getGeekLike($suggest, $gender)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('g')
            ->from('FionaGeekticCoreBundle:Geek','g')
            ->orderBy('g.firstname','ASC')
        ;

        $orModule = $queryBuilder->expr()->orx();
        $orModule->add($queryBuilder->expr()->like('g.firstname',':suggestBoth'));
        $orModule->add($queryBuilder->expr()->like('g.lastname',':suggestBoth'));
        $queryBuilder->andWhere($orModule);
        $queryBuilder->setParameter('suggestBoth',"%".$suggest."%");

        if ($gender != 'BOTH') {
            $queryBuilder->andWhere('g.gender = :gender');
            $queryBuilder->setParameter('gender',$gender);
        }

        return $queryBuilder->getQuery()->getResult();
    }


}
