fiona_geek2geek_core_homepage:
    path:     /
    defaults: { _controller: FionaGeek2geekCoreBundle:Home:home}

fiona_geek2geek_core_search:
    path:     /search
    defaults: { _controller: FionaGeek2geekCoreBundle:Search:search}

fiona_geek2geek_core_profile:
    path:     /profile/{id}
    defaults: { _controller: FionaGeek2geekCoreBundle:Profile:profile, id:-1}
